language: scala
scala:
    - 2.12.8
jdk:
    - openjdk8
sudo: false
install: true
script:
    - sbt clean scalastyle coverage test coverageReport
    - sbt coverageAggregate
after_success:
    - sbt coveralls
