version: '2'
services:
  node:
    container_name: cc_worker
    image: simple-worker
    environment:
      CLUSTER_PORT: 1606
      CLUSTER_IP: node
      SEED_PORT_1600_TCP_ADDR: master
      SEED_PORT_1600_TCP_PORT: 1600
      WORKER_MONGODB_URL: mongodb://root:example@host.docker.internal:27017
      WORKER_EXECUTE_INTERVAL: 30.seconds
  master:
    container_name: cc_master
    image: master:latest
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: master
      SEED_PORT_1600_TCP_ADDR: master
      MONGO_PROVIDER_CONNECTION_STRING: mongodb://root:example@host.docker.internal:27017
  tor:
    image: arulrajnet/torprivoxy
    ports:
      - 9050:9050
      - 9051:9051
      - 8118:8118
    volumes:
      - ./torrc:/opt/tor/torrc
