version: '3.7'
services:
  worker:
    container_name: cc_worker
    image: simple-worker:latest
    environment:
      MASTER_GRPC_HOST: master
      WORKER_MONGODB_URL: mongodb://mongodb:27017
      WORKER_EXECUTE_INTERVAL: 30.seconds
  master:
    container_name: cc_master
    image: master:latest
    environment:
      MONGO_PROVIDER_CONNECTION_STRING: mongodb://mongodb:27017
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
  tor:
    image: peterdavehello/tor-socks-proxy:latest
