name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get current branch
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
      - name: Run compile
        run: sbt compile
      - name: Scalastyle
        run: sbt scalastyle
      - name: Test and Coverage
        run: sbt coverage test coverageReport
      - name: Coverage Aggregate
        run: sbt coverageAggregate
      - name: Push Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS }}
          CI_BRANCH: ${{steps.branch.outputs.branch}}
        run: sbt coveralls
