name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF:10})"
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
      - name: Scalastyle
        run: sbt scalastyle
      - name: Login to GitHub Docker Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.GITHUB_DOCKER_USERNAME }} --password-stdin
      - name: SBT image build
        run: sbt docker:publishLocal
      - name: Docker tag
        run: docker tag master:latest docker.pkg.github.com/jaitl/cloud-crawler/master:${RELEASE_VERSION}
        env:
          RELEASE_VERSION: ${{steps.version.outputs.version}}
      - name: Docker push
        run: docker push docker.pkg.github.com/jaitl/cloud-crawler/master:${RELEASE_VERSION}
        env:
          RELEASE_VERSION: ${{steps.version.outputs.version}}
      - name: Publish to bintray
        env:
          - BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          - BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
          - RELEASE_VERSION: ${{steps.version.outputs.version}}
        run: sbt publish
